// GENERATED by scripts/sw.mjs — do not edit, edit the generator.
const VERSION = "assetsindex-CkZjcsFr.js";
const CACHE = "posfix-" + VERSION;
// Product / category photos live in their OWN cache, separate from the version
// cache, so a deploy does not wipe every picture a staff member has already
// downloaded. The version cache is retired wholesale on every build; these must
// not be. Staleness is not a risk: a download URL token changes when the
// picture changes, so an updated photo has a URL this cache has never seen and
// re-downloads on its own.
const IMG_CACHE = "posfix-images";
const PRECACHE = [
  "/apple-touch-icon.png",
  "/assets/index-CkZjcsFr.js",
  "/assets/ponyfill-BuxwROcg.js",
  "/icon-192.png",
  "/icon-512.png",
  "/index.html",
  "/manifest.json",
  "/posfix-logo.png"
];

// ignoreVary is not a nicety, it is the difference between working and not.
// The host answers assets with "Vary: Origin". This worker precaches them with
// a plain same-origin request, which carries NO Origin header, while the page
// asks for its own bundle through a crossorigin module script, which carries
// one. Those two do not match, so every lookup missed and an offline reload
// gave a blank page and ERR_FAILED on the one file that mattered — with the
// file sitting in the cache the whole time.
const MATCH = { ignoreVary: true };

self.addEventListener("install", (e) => {
  // One failed URL rejects addAll and the whole worker never installs, taking
  // offline support with it silently. Each file is fetched on its own so a
  // single missing icon cannot do that.
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    await Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: "reload" })).catch(() => {})));
    // Safe here: the app is ONE bundle with no code splitting, so a page that
    // is already running cannot ask for a chunk this worker would answer from
    // a newer build.
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE && n !== IMG_CACHE).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);

  // ── Product / category photos (Firebase Storage) ─────────────────────────
  // The counter's pictures live in Firebase Storage, not Firestore. Firestore
  // caches its own data for offline; Storage does not, and this worker has
  // always let cross-origin traffic pass straight through, so a product photo
  // was a broken image the moment the line dropped.
  //
  // Cache those responses here, cache-first: the first time a staff member
  // sees a product online, its picture is stored, and every offline open after
  // that draws the same picture from the cache. A download URL carries a token
  // that changes when the picture changes, so an updated product has a new URL,
  // misses this cache, and re-downloads on its own — no invalidation needed.
  //
  // The request is no-cors, so the response is opaque (status 0). cache.add()
  // refuses an opaque response; cache.put() accepts it, and caches.match()
  // hands it back exactly as the <img> expects. Only image requests are
  // touched: this origin serves nothing else in this app.
  if (url.hostname === "firebasestorage.googleapis.com" && req.destination === "image") {
    e.respondWith((async () => {
      const hit = await caches.match(req, MATCH);
      if (hit) return hit;
      const res = await fetch(req);
      if (res) (await caches.open(IMG_CACHE)).put(req, res.clone());
      return res;
    })());
    return;
  }

  // Cross-origin is Firestore, Google sign-in and the canary. Touching any of
  // it would be meddling in a live connection to look clever.
  if (url.origin !== self.location.origin) return;

  // The update check asks to bypass caches, and it must get its wish or it
  // would compare a build against itself and never see a deploy.
  //
  // ONLY no-store. "reload" looks like it belongs here and does not: pressing
  // reload makes the browser mark every subresource on the page that way, so
  // skipping those meant the bundle itself was never served from the cache —
  // offline reload gave a blank page with ERR_FAILED on the one file that
  // mattered, while the cache sat there holding it.
  if (req.cache === "no-store") return;

  // Content-hashed and immutable: a changed file has a changed name.
  if (url.pathname.startsWith("/assets/")) {
    e.respondWith((async () => {
      const hit = await caches.match(req, MATCH);
      if (hit) return hit;
      const res = await fetch(req);
      if (res && res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    })());
    return;
  }

  // Everything else: network first, cache only when the network fails.
  e.respondWith((async () => {
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === "basic") {
        (await caches.open(CACHE)).put(req, res.clone());
      }
      return res;
    } catch (err) {
      const hit = await caches.match(req, MATCH);
      if (hit) return hit;
      // A navigation with nothing cached for that exact URL still has to land
      // somewhere: this is a single-page app, so the shell is the right answer
      // for any route.
      if (req.mode === "navigate") {
        const shell = await caches.match("/index.html", MATCH);
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
